version: '3.6'
services:

  mongo_bitcoders:
    image: mongo:6.0.3
    container_name: mongo_bitcoders
    restart: always
    env_file:
      - .env
#    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./.docker/mongo-volume:/data/db
      - ./.docker/mongo-logs:/var/log/mongodb
    #      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - bitcoders

  rabbitmq_bitcoders:
    image: rabbitmq:3.9-management
    container_name: rabbitmq_bitcoders
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_USERNAME: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bitcoders

networks:
  bitcoders:
    driver: bridge
