version: '3.8'
services:

  bitcoders_nest:
    build: .
    container_name: bitcoders-nest
    command: [ "npm", "run", "rest" ]
    restart: always
    ports:
      - '9087:9087'
    env_file:
      - ./.env
    networks:
      - cluster_network
    depends_on:
      - mongo_bitcoders
#      - redis_nest
#      - rabbitmq_nest

  mongo_bitcoders:
    image: mongo:latest
    container_name: mongo_bitcoders
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
#      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./.docker/mongo-volume:/data/db
      - ./.docker/mongo-logs:/var/log/mongodb
#      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - cluster_network

#  redis_nest:
#    container_name: redis
#    env_file:
#      - .env
#    image: redis:latest
#    restart: always
#    volumes:
#      - ./.docker/redis-data:/var/lib/redis
#      - ./.docker/redis-conf:/usr/local/etc/redis
#    ports:
#      - '6389:6379'
#    networks:
#      - cluster_network

##  rabbitmq_nest:
##    image: rabbitmq:3.9-management
##    container_name: rabbitmq_nest
##    restart: always
##    env_file:
##      - .env
##    environment:
##      RABBITMQ_USER: ${RABBITMQ_USER}
##      RABBITMQ_HOST: ${RABBITMQ_HOST}
##      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
##      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
##      RABBITMQ_USERNAME: ${RABBITMQ_USER}
##      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
##      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
##      RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
##      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
##      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log [{console,[{level,debug}]}]
##    command: [ "bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server" ]
##    volumes:
##      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
##      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
##    ports:
##      - "5671:5671"
##      - "5672:5672"
##      - "15671:15671"
##      - "15672:15672"
#    networks:
#      - cluster_network

networks:
  cluster_network:
    driver: bridge
