version: '3.6'
services:

  websocket_bitcoders:
    container_name: websocket_bitcoders
    build:
      context: .
    command: [ "npm", "run", "sock:prod" ]
    restart: always
    env_file:
      - .env.docker
    ports:
      - '8000:8000'
    networks:
      - bitcoders

  rest_bitcoders:
    container_name: rest_bitcoders
    build:
      context: .
    command: ["npm", "run", "rest:prod"]
    restart: always
    env_file:
      - .env.docker
    ports:
      - '9087:9087'
    networks:
      - bitcoders
    depends_on:
      - mongo_bitcoders

  mongo_bitcoders:
    image: mongo:6.0.3
    container_name: mongo_bitcoders
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./.docker/mongo-volume:/data/db
      - ./.docker/mongo-logs:/var/log/mongodb
    #      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"

    networks:
        - bitcoders

networks:
  bitcoders:
    driver: bridge
