version: '3.8'
services:

  nest_bitcoders:
#    image: bitcodersnest-bitcoders_nest:latest
    container_name: nest_bitcoders
    build: .
    command: ["npm", "run", "rest:prod"]
    restart: always
    ports:
      - '9087:9087'
    env_file:
      - .env
#    networks:
#      - cluster_network
#    depends_on:
#      - mongo_bitcoders

#  nest_bitcoders:
#    build: .
#    container_name: nest_bitcoders
#    command: [ "npm", "run", "rest:prod" ]
#    restart: always
#    ports:
#      - '9087:9087'
#    env_file:
#      - ./.env
#    networks:
#      - cluster_network
#    depends_on:
#      - mongo_bitcoders
##      - redis_nest
##      - rabbitmq_nest
#  redis_nest:
#    container_name: redis
#    env_file:
#      - .env
#    image: redis:latest
#    restart: always
#    volumes:
#      - ./.docker/redis-data:/var/lib/redis
#      - ./.docker/redis-conf:/usr/local/etc/redis
#    ports:
#      - '6389:6379'
#    networks:
#      - cluster_network

##  rabbitmq_nest:
##    image: rabbitmq:3.9-management
##    container_name: rabbitmq_nest
##    restart: always
##    env_file:
##      - .env
##    environment:
##      RABBITMQ_USER: ${RABBITMQ_USER}
##      RABBITMQ_HOST: ${RABBITMQ_HOST}
##      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
##      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
##      RABBITMQ_USERNAME: ${RABBITMQ_USER}
##      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
##      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
##      RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
##      RABBITMQ_EXCHANGE: ${RABBITMQ_EXCHANGE}
##      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log [{console,[{level,debug}]}]
##    command: [ "bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server" ]
##    volumes:
##      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
##      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
##    ports:
##      - "5671:5671"
##      - "5672:5672"
##      - "15671:15671"
##      - "15672:15672"
#    networks:
#      - cluster_network

networks:
  cluster_network:
    driver: bridge
