version: '3.6'
services:

  websocket_bitcoders:
    container_name: websocket_bitcoders
    build:
      context: .
    command: [ "npm", "run", "sock:prod" ]
    restart: always
    env_file:
      - .env
    ports:
      - '8000:8000'
    networks:
      - bitcoders

  rest_bitcoders:
    container_name: rest_bitcoders
    build:
      context: .
    command: ["npm", "run", "rest:prod"]
    restart: always
    env_file:
      - .env
    ports:
      - '9087:9087'
    networks:
      - bitcoders

  serv_bitcoders:
    container_name: serv_bitcoders
    build:
      context: .
    command: [ "npm", "run", "serv:prod" ]
    restart: always
    env_file:
      - .env
    networks:
      - bitcoders

  mongo_bitcoders:
    image: mongo:6.0.3
    container_name: mongo_bitcoders
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./.docker/mongo-volume:/data/db
      - ./.docker/mongo-logs:/var/log/mongodb
    #      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - "27017:27017"
    networks:
      - bitcoders

  rabbitmq_bitcoders:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_USERNAME: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
    # RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log [{console,[{level,debug}]}]
    # command: [ "bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server" ]
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - bitcoders

networks:
  bitcoders:
    driver: bridge
